<section>
	<div class="vh-120 hidden-xs">&nbsp;</div>
	<div class="vh-20 visible-xs">&nbsp;</div>
	<div id="page"></div>
</section>
<script>
	/** User Account **/
	_('api/session')
		.takeAction(function(val, json) {
			var pageName	= 'public';
			var username 	= val.username;
			var signedIn	= false;

			if (username == 'Visitor' || username == '') {
			} else {
				signedIn 	= true;
				pageName	= 'member';
			}

			onServer.page(pageName+'/home', '#page');
		})
	;
</script>